---
title: "`r emo::ji('runner')` Hastings Half-Marathon Maps"
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "Author", href: "https://www.matt-dray.com/", align: right }
      - { title: "Source", href: "https://www.github.com/matt-dray/hastings-half/", align: right }
      - { title: "Official Site", href: "https://www.hastings-half.co.uk/", align: right }
    theme:
      fg: "#000000"
      bg: "#FFFFFF"
      primary: "#B12923"
      navbar-bg: "#B12923"
      base_font:
        google:
          family: "Arvo"
      code_font:
        google:
          family: "Arvo"
---

```{r}
#| name = "setup",
#| include = FALSE

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

thematic::thematic_rmd(font = "auto")
col_red <- "#B12923"
```

```{r}
#| name = "attach-pkgs"

suppressPackageStartupMessages({
  library(ggplot2)
  library(plotly)
  library(rgl)
  library(ggrgl)
  library(devoutrgl)
  library(grDevices)
  library(gpx3d)
  library(leaflet)
  library(sf)
  library(units)
})
```

```{r}
#| name = "prep-data"

file <- "data/route_2022-03-20_12.16pm.gpx"
route <- extract_gpx3d(file)

route_min <- route[seq(1, nrow(route), 20), ]
route_min_lines <- st_cast(route_min, "LINESTRING")
route_min_multilines <- st_cast(route_min_lines, "MULTILINESTRING")

route$distance <- as.numeric(route$distance)
route$distance_cum <- cumsum(route$distance)
```

```{r}
#| name = "prep-leaflet"

ks <- seq(1000, 21000, 1000)

k_indices <- c()

for (k in ks) {
  k_index <- which.min(abs(route$distance_cum - k))
  k_indices <- c(k_indices, k_index)
}

kstones <- route[k_indices, ]

map_leaflet <- leaflet() |> 
  addProviderTiles("CartoDB.Voyager") |> 
  addPolylines(
    route_min$lon,
    route_min$lat,
    color = col_red
  ) |> 
  addAwesomeMarkers(
    c(kstones[["lon"]], route[1, ][["lon"]]),
    c(kstones[["lat"]], route[1, ][["lat"]]),
    icon = awesomeIcons(
      text = paste(0:21),
      fontFamily = "sans-serif",
      markerColor = col_red
    )
  )
```

```{r}
#| name = "prep-plotly"

prep_plotly_profile <- route |> 
  ggplot(aes(distance_cum, ele)) +
  geom_path(
    aes(
      group = as.Date(time),
      text = paste(
        "Distance:", round(distance_cum / 1000, 1), "km\n",
        "Elevation:", round(ele), "m"
      )
    ),
    colour = col_red,
    size = 2
  ) +
  xlab("Distance (km)") +
  ylab("Elevation (m)") +
  theme_void()

map_plotly_profile <- ggplotly(tooltip = "text") |> 
  config(displayModeBar = FALSE)
```

```{r}
#| name = "prep-plotly-3d"

map_plotly_3d <- plot_ly(
  x = ~route$lon,
  y = ~route$lat,
  z = ~route$ele,
  type = "scatter3d",
  mode = "lines",
  line = list(color = col_red, width = 10, alpha = 1)
) |> 
  layout(
    scene = list(
      xaxis = list(title = "Longitude"),
      yaxis = list(title = "Latitude"),
      zaxis = list(title = "Elevation (m)")
    )
  ) |> 
  config(displayModeBar = FALSE)
```

Column {.tabset}
-------------------------------------

### `r emo::ji("bird")` Route

```{r}
#| name = "output-leaflet"
map_leaflet
```

### `r emo::ji("mountain")` Profile

```{r}
#| name = "output-plotly-profile"
map_plotly_profile
```

### `r emo::ji("globe_with_meridians")` 3D

```{r}
#| name = "plot-plotly-3d"
map_plotly_3d
```

<!-- ```{r} -->
<!-- #| name = "prep-ggrgl" -->

<!-- map_ggrgl <- route |>  -->
<!--   ggplot() + -->
<!--   geom_path_3d( -->
<!--     aes(lon, lat, z = ele), -->
<!--     extrude = TRUE, -->
<!--     extrude_edge_colour = "#000000", -->
<!--     extrude_face_fill = col_red, -->
<!--     extrude_edge_alpha = 0.2 -->
<!--   ) +  -->
<!--   theme_void() -->
<!-- ``` -->

<!-- ### `r emo::ji("globe_with_meridians")` Route 3D -->

<!-- ```{r} -->
<!-- #| name = "output-ggrgl", -->
<!-- #| fig.showtext = TRUE, -->
<!-- #| error = FALSE -->

<!-- rgldev(fov = 30, view_angle = -30) -->
<!-- map_ggrgl -->
<!-- invisible(dev.off()) -->
<!-- if (!interactive()) rglwidget() -->
<!-- ``` -->
